sonata_admin:
    title:      Presta CMS Sandbox
    templates:
        # default global templates
        layout:  ApplicationSonataAdminBundle::custom_layout.html.twig
    dashboard:
        blocks:
            -
                position: left
                type: sonata.block.service.text
                settings:
                    content: |
                        <h2>Welcome in Presta CMS Sandbox</h2>
                        <p>
                            This is an early release and will be enhanced progressively.
                        </p>
                        <p>
                            Right now features are :
                            <ul>
                                <li>Multiple websites by configuration</li>
                                <li>Multilangue</li>
                                <li>Custom theming</li>
                                <li>Page administration</li>
                            </ul>
                        </p>
                        <p>
                            You can use it freely for your project, open / correct tickets on Github via Pull request.
                        </p>
                        <p>
                            We hope it will help you on your project.
                        </p>
                        <p>
                            Presta CMS is based on Symfony CMF so we would like to thanks people working on it.
                        </p>
                        <p>
                            Presta CMS is sponsored by <a href="www.prestaconcept.net">PrestaConcept</a>
                        </p>
            - { position: right, type: sonata.admin.block.admin_list }
        groups:
            sonata_media: ~

            presta_cms_contact:
                label_catalogue: PrestaCMSContactBundle
                items:
                    - presta_cms_contact.admin.contact
                    - presta_cms_contact.admin.message
