imports:
    - { resource: parameters.yml }
    - { resource: phpcr_doctrine_dbal.yml }
    - { resource: security.yml }
    - { resource: '@PrestaCMSCoreBundle/Resources/config/config.yml' }
    - { resource: bundles/sonata_admin.yml }
    - { resource: bundles/sonata_block.yml }
    - { resource: bundles/sonata_media.yml }
    - { resource: bundles/presta_cms_core.yml }
    - { resource: bundles/stfalcon_tinymce.yml }
    - { resource: bundles/presta_cms_contact.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        - ApplicationSonataAdminBundle
        - ApplicationPrestaCMSCoreBundle
        - PrestaCMSCoreBundle
        - PrestaCMSThemeBasicBundle
        - PrestaCMSContactBundle

    filters:
        cssrewrite: ~
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to: "\.less$"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        path:     "%database_path%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# cmf configuration
doctrine_phpcr:
    # configure the PHPCR session
    session:
        backend: %phpcr_backend%
        workspace: %phpcr_workspace%
        username: %phpcr_user%
        password: %phpcr_pass%
    # enable the ODM layer
    odm:
        auto_generate_proxy_classes: %kernel.debug%
        locales:
            en:
                - fr
            fr:
                - en
        #auto_mapping: true
        #auto_mapping is not working due to a MappingException in Sonata Media
        #Invalid mapping file 'Sonata.MediaBundle.Document.BaseGallery.phpcr.xml' for class 'Sonata\MediaBundle\Document\BaseGallery'
        document_managers:
            default:
                mappings:
                    ApplicationPrestaCMSCoreBundle: ~
                    PrestaCMSCoreBundle: ~
                    CmfRoutingBundle: ~
                    CmfTreeBrowserBundle: ~
                    SonataDoctrinePHPCRAdminBundle: ~
                    CmfBlockBundle: ~
                    CmfContentBundle: ~
                    CmfMenuBundle: ~
                    CmfCoreBundle: ~

knp_menu:
    twig: true
